name: Build EXE for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5 pyserial

    - name: Build EXE using PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico main.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: cashier-app-exe
        path: dist/main.exe
